### ISSUE TITLE
[C16] issues in core 190504

### ISSUE THREAD

**Issue by nippur72** [mist-devel/mist-board#108]
with latest C16 core `c16_190504.rbf`, the BASIC commands
```
GRAPHIC 2:CIRCLE 1,40,40,30,30
```
cause a BRK instruction (enters in MONITOR) instead of drawing a circle.

**Comment by lroby74** [comment]
I've tried with lastest RBF previous external mandatory C16.ROM and it works fine.
Something is gone wrong in lastest version
