### ISSUE TITLE
Feature request: assign OSD settings through ini file

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-board#116]
If a core has a say "difficulty" setting in the OSD menu, it would be nice if the user could add that to the ini file. That way the user doesn't have to set it up manually each time the core is loaded.

**Comment by gyurco** [comment]
Doesn't "Save settings" work? It should save all OSD settings.

**Comment by jotego** [comment]
I didn't know it saved core-specific data too. It does work. Thanks!
