### ISSUE TITLE
VIC20 screen on NTSC

### ISSUE THREAD

**Issue by DFL1973** [mist-devel/mist-board#126]
Vic20 screen is 1/4 off the center in NTSC mode. The left border and the first columns of the characters are off the screen.

PAL mode is perfect

**Comment by harbaum** [comment]
If you run a ntsc cartridge on pal hardware then this is normal. This even happens on the real device.

**Comment by DFL1973** [comment]
Even at the boot screen? (no cartridge)

It´s unusable on NTSC. You can't see what you are typing. (the first letters, I mean)

**Comment by gyurco** [comment]
Try this one:
https://github.com/gyurco/VIC20_MiST/releases/tag/20191026
It's better on my displays.

**Comment by DFL1973** [comment]
It cuts the left border at the half, but the "middle" screen is totally visible now.

Thanks!
