### ISSUE TITLE
Load/save issue?

### ISSUE THREAD

**Issue by dfilskov** [mist-devel/mist-board#129]
This is an issue on the MiSTer core but I think it's an issue with this core too.

I've composed a bunch of tunes for Gameboy almost 20 years ago - but it doens't work when I load them into SRAM for the Carillon Editor (copying it to the sdcard overwriting an already existing save - carillon.sav ). The data doesn't seem to get loaded.

I've attached the .gb for Carillon Editor - and .bin and .sav files for one of my tunes for testing.

[gameboy-save-load-issue.zip](https://github.com/mist-devel/mist-board/files/3911110/gameboy-save-load-issue.zip)

The Carillon Editor author Alexi Eeben wrote about this issue:
"maybe it’s ”emulating” a wrong memory controller? The old flash carts were (if I recall correctly) of type MBC5"

In Carillon Editor ...
Load tune = click Start button on LOAD FROM SRAM
Play = click Start twice on BLOCK ORDER LIST
Save tune = click Start on STORE IN SRAM

Any ideas how to make it work?

**Comment by gyurco** [comment]
Currently no RAM implemented in any cart space.
Upd.: I was wrong, cart RAM is implemented. Have to check the actual cart dump.
Saving/loading of RAM is not done on MiST.

**Comment by dfilskov** [comment]
Great :) - thanks for looking into this!

Not sure what you mean it's not done ... you mean it's only MiSTer that's supposed to be able to do this?

Perhaps it could be copied from the MiSTer core - and fixed in both MiST and MiSTer? :)

Here's this MiSTer issue:
https://github.com/MiSTer-devel/Gameboy_MiSTer/issues/61

**Comment by dfilskov** [comment]
Wait ... - it works!! - the SRAM file wasn't loaded unless I booted the ROM file again. My mistake!

Check this out :)
https://www.dropbox.com/s/k668zoxfbkdp03i/Evil%20Mirror%20winner.mp4?dl=0
