### ISSUE TITLE
SCART video cable; 50Hz only?

### ISSUE THREAD

**Issue by boomlinde** [mist-devel/mist-board#136]
On TV output via SCART, the wiki notes:

> The video signal must be a 15kHz/50Hz PAL signal.

I have TVs that accept 60 Hz RGB over SCART. Is there something about the cable or the MiST itself which prevents using 60 Hz over SCART, is it an error in the documentation or is it simply rare that a TV can handle such a signal?

**Comment by harbaum** [comment]
The cable is a pure passive thing and would simply forward any signal. However SCART imho only existed in PAL world and officially only supported PAL frequencies. So it depends on the TV if it also supports NTSC over SCART.

**Comment by gyurco** [comment]
My TV doesn't have any problems with NTSC signal on SCART.

**Comment by boomlinde** [comment]
I have been able to confirm that this works with TVs that support it.
