### ISSUE TITLE
Sega Megadrive controllers on the 9-pin ports

### ISSUE THREAD

**Issue by boomlinde** [mist-devel/mist-board#137]
Is it possible to use Sega three- or six button joypads with the MiST? The wiki notes here that Atari-style joysticks are supported, but I've seen other sources suggest that you can use a Sega three button joypad. If so, can all the buttons be used in the Sega Megadrive core?

**Comment by harbaum** [comment]
No, they don't work. But you can use a Megadrive to USB converter.

**Comment by boomlinde** [comment]
Thank you, that's a good idea!

**Comment by manast** [comment]
I wonder, how much latency is expected by using the USB controller instead of the Joystick input?
