### ISSUE TITLE
install_arm-none-eabi-gcc.sh is not complete

### ISSUE THREAD

**Issue by sorgelig** [mist-devel/mist-board#14]
Building of gcc has failed because required libs are missing: MPC, MPFR, GMP
I believe some linux distro have these libraries installed and thus gcc will be built successfully, but for general case it's better to download these libs and put into gcc source folder - and they will be automatically picked by compiler. 
That's how i've compiled it in Ubuntu 14.1.  

I hope i won't need ARM JTAG soon ;)

**Comment by harbaum** [comment]
That should just be a matter of apt-get installing the apropriate -dev packages. That works at least for all the ubuntu versions I've used so far incl 15.10.

The arm flasher nowadays also needs a small fix. I should actually document these.

**Comment by harbaum** [comment]
Added some remarks regarding the libraries to 
https://github.com/mist-devel/mist-board/wiki/HowToCompileTheFirmware
