### ISSUE TITLE
Ploblem C64 Core

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-board#141]
Hi.
Problem the last version of Mist FPGA64 Core related to boot.
Test:
First boot...... black screen and core is running (F12 Works).

Solution (temp.):
change to old core and re run the new. 

its like how the ROM loader not work properly.

Thanks.

**Comment by gyurco** [comment]
You need the latest firmware (2003111)
https://github.com/mist-devel/mist-binaries/blob/master/firmware/firmware_200311.upg

**Comment by Julitium** [comment]
Mist Updated.... Its Works!!!
Thanks.
