### ISSUE TITLE
Problem ZX80/81 Core

### ISSUE THREAD

**Issue by Julitium** [mist-devel/mist-board#142]
Hi.
The ZX8X core not works for me..... always black screen with no f12 or any other function, its looks freeze.
Test:
RGB Cable and screendoubler disabled.

Always fail.....All versions.

Thanks.

**Comment by gyurco** [comment]
The ROM file is in place?

**Comment by Julitium** [comment]
The ROM is in place! (zx8x.rom  12kb)
Not work :-(

P. D: zx48 core and zx48.rom (16kb) Works but its old.

**Comment by harbaum** [comment]
Did you try a different screen? Maybe your screen simply doesn't cope with the video timing of a  zx81

**Comment by gyurco** [comment]
Maybe would be better to have ZX81 as the default, not ZX80. At least the hsync is hardware generated on that.

**Comment by Julitium** [comment]
Tim is in right..... At VGA monitor its Works!!!.
Now, i Will do the default in Zx81 Gyurco.
Thanks.

**Comment by Julitium** [comment]
Gyurco is in Right.... Default to Zx81 Works fine!!!.
Thank you.

**Comment by Julitium** [comment]
Now its Works on my rgb 15khz.
