### ISSUE TITLE
Firmware: exFAT support

### ISSUE THREAD

**Issue by solskogen** [mist-devel/mist-board#143]
Sometimes it would be awesome to have files bigger than 4GB on the SD card (big hdf's for example), but that is not possible at the moment.

**Comment by jotego** [comment]
I think it will be hard to find an exFAT implementation for the microcontroller.

**Comment by harbaum** [comment]
Also the SD card in the mist is rather slow. So there's basically no valid use case for gigabytes of data. It would take the mist several days to read that. And if you only use a fraction of the image you can likely live with less than 2gb max image size.

**Comment by solskogen** [comment]
It works quite well on MiSTer when I have hdf files that are 8GBs (for the
whole WHDL collection)

**Comment by gyurco** [comment]
With direct SD access, it's about 1 megabytes/sec. With sequential read you could read 8 GiB in 8000 secs. Random reads and writes will take forever.
Btw, I don't think there's enough Flash/RAM for an exFAT implementation.

**Comment by gyurco** [comment]
If still interested:
https://www.atari-forum.com/viewtopic.php?f=115&t=40499

**Comment by gyurco** [comment]
Latest firmware supports the exFAT filesystem.
