### ISSUE TITLE
Amstrad CPC+ / GX-4000

### ISSUE THREAD

**Issue by micv2** [mist-devel/mist-board#144]
Hello, is there a way to play the Amstrad CPC + / GX-4000 stuff on the MiST? There are many homebrew productions, and of course demos .. :) 
Best regards, MiC

https://www.youtube.com/watch?v=PgMJ39wfoBM&feature=youtu.be

**Comment by sorgelig** [comment]
No.
CPC+/GX4000 uses different ASIC which is not implemented.

**Comment by micv2** [comment]
Ok, thanks

Von meinem Handy gesendet

**Comment by gyurco** [comment]
It won't be implemented in the near future, I think.

**Comment by sorgelig** [comment]
it will wait for another CPC addicted developer :)
