### ISSUE TITLE
Is it a possible to boot using an ARC file instead of core.rbf?

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-board#145]
Now somre RBF files depend on information present in the ARC. How do you do it to boot from an ARC files instead of core.rbf?

**Comment by gyurco** [comment]
Sorry, currently it's not possible.

**Comment by jotego** [comment]
Ok. Thank you.

**Comment by gyurco** [comment]
Just added CORE.ARC file support to the firmware.

**Comment by jotego** [comment]
Thank you! I'll look for the binary
