### ISSUE TITLE
Documentation on using pages on ARC files

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-board#153]
Can you point to some example of pages in the OSD for ARC files? I'd like to use them. I will also update the Wiki to document their usage. I think the MRA tool support that, didn't it?

Thanks

**Comment by gyurco** [comment]
They're in your jtbin repo :)
The MRA tool supports it, but currently one page only (as it supports one swtiches block).
Check the latest CPS1 mra commit, if you generate the ARC file from those MRAs, then you'll see the usage.
