### ISSUE TITLE
zx spectrum core

### ISSUE THREAD

**Issue by thecaver99** [mist-devel/mist-board#155]
change the multiface to something like F10 so its easier and quicker to use and remove the default genie to the alt part instead of the other way round

**Comment by gyurco** [comment]
Genie can be disabled, but cannot be re-enabled. That's how the original Multiface works.

**Comment by thecaver99** [comment]
No but it can be loaded from tape into the 8k ram as thats how did it back
in the day with them

**Comment by gyurco** [comment]
Actually you can create your own spectrum.rom without Genie:
https://github.com/mist-devel/mist-binaries/tree/master/cores/spectrum#rom-format

**Comment by gyurco** [comment]
The latest core has F10 as NMI key, F11 as reset.
