### ISSUE TITLE
Nice smoke test for the C= 64 core

### ISSUE THREAD

**Issue by ArKay74** [mist-devel/mist-board#21]
This demo seems to work only on real hardware and in micro64. VICE, Emu64 and MiST fail.

http://csdb.dk/release/?id=146723

**Comment by harbaum** [comment]
Yes, the C64 isn't perfect. It's license isn't 100% clear. We got permission from the origjnal author to publish cores based on it. But we cannot simply share the source and thus it doesn't get much attention I am afraid.

**Comment by ArKay74** [comment]
I have the feeling that there isn't much missing so that's really sad. 
How cool it would be if it would run this demo
which has received quite some attention. The guy who tested 37 games on 
YT only had problems with a few of them.
So we can only hope for the Mega65 to get it right then.

**Comment by harbaum** [comment]
Actually the last 10% of the games and demos require 90% of the coding effort.

These are the games and demos that rely on perfect timing which often means that you need to rewrite everything. 

I don't know how precise the Mega65 core is with respect to the C64. But it's not a them or us thing. These cores usually run with little effort on different machines. So it would definitely be possible to run the Mega65 code on the mist and vice versa of course).

**Comment by juri74** [comment]
hello, where is the RESTORE key mapped? can't find it..

**Comment by gyurco** [comment]
I think this demo works well now.
