### ISSUE TITLE
TRS-80 core?

### ISSUE THREAD

**Issue by EricGus** [mist-devel/mist-board#23]
Was just looking to see if a TRS 80 core was available .. I see other Z80 based systems that are more complex that the TRS80..

**Comment by vodkaflip** [comment]
Can I second that request? It seems like the TRS-80 was done as part of the zxgate project, but the ROMs are missing (cannot be distributed?!?). The zx01 core seems to use files as hosted on  http://zxgate.cvs.sourceforge.net/viewvc/zxgate so I am hoping the TRS80 (and Jupiter Ace) can be added as well!

**Comment by gyurco** [comment]
HT1080Z is a TRS-80 Model-I clone.
