### ISSUE TITLE
Would this support Master System/Genesis joysticks?

### ISSUE THREAD

**Issue by arromdee** [mist-devel/mist-board#34]
They use the same joystick port as the Atari joysticks so I wonder if it would be possible to support them (at least if anyone ever writes a Genesis core).

**Comment by harbaum** [comment]
They share the same connector, true. But the signals differ according to this page:
http://www.picaxeforum.co.uk/showthread.php?27553-Reading-the-Sega-Mega-Drive-Genesis-control-pads

But you could always use a device like this:
http://www.retrousb.com/product_info.php?products_id=69
to connect the Genesis controller to the MISTs USB ports. The same approach is being used when connecting original Atari Paddles to the MIST: 

https://www.youtube.com/watch?v=nyR-TPYOdvU
