### ISSUE TITLE
Support for Commodore / Atari Mouse, Dual Mouse-Support

### ISSUE THREAD

**Issue by uchristo** [mist-devel/mist-board#51]
What is needed to enable native Mouse-Support? I'd like to play Settlers in Splitscreen. Afaik USB-HIDs will not allow the use of two Mice simultaneously...

**Comment by harbaum** [comment]
There's no technical reason why you cannot connect two USB mice. 

What system are we talking about? Atari ST? Amiga?

**Comment by uchristo** [comment]
I'm talking about the Amiga Core. So conneciting (and using) two USB Mice would be possible?

**Comment by gyurco** [comment]
You can play  Settlers with two mice now!
