### ISSUE TITLE
Wrong scart cable schematic

### ISSUE THREAD

**Issue by kiwanowski** [mist-devel/mist-board#59]
The VGA plug in the scart cable schematic is mirrored - https://github.com/mist-devel/mist-board/wiki/ScartCable

**Comment by harbaum** [comment]
It depends from which side you look onto the plug. If you look from the rear side (where you solder the cables to) then this is correct. When you watch it from the front that plugs into the PC then this is indeed wrong.

**Comment by kiwanowski** [comment]
https://www.arcade-projects.com/forums/index.php?attachment/5125-vga-pinout-jpg/ - look at the pinout. Pin number 10 should be indented. The vga connector is made like this so it doesnt matter at which side are you looking at

**Comment by harbaum** [comment]
Ah, i see. Yes. Indeed

**Comment by harbaum** [comment]
Fixed

**Comment by harbaum** [comment]
P.S.: The PDF is also fixed
