### ISSUE TITLE
Archimedes RISCOS in German

### ISSUE THREAD

**Issue by Silent-Hunter** [mist-devel/mist-board#66]
For some reason, on the Acorn Archimedes core, every riscos rom I try is in German. I'm sure it's not the roms, as there's no mention of them being a German version.

**Comment by terriblefire** [comment]
There are all different language versions of RISC OS. I think the german version is 3.19 which. 

Try 3.10 or 3.11.

**Comment by harbaum** [comment]
The core is just the hardware. It knows nothing about languages. It must be in the rom.
